// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDebP8Z4auyoR4WnOLJpaqmlKNV71BuNX4',
    appId: '1:892493235707:web:220eb5c2cca7f53c48b75e',
    messagingSenderId: '892493235707',
    projectId: 'kiloapp-bfdaa',
    authDomain: 'kiloapp-bfdaa.firebaseapp.com',
    storageBucket: 'kiloapp-bfdaa.firebasestorage.app',
    measurementId: 'G-59PR41SH2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb9pQ5K3ymwV2KVlOVcBw7c4HRfSg5DCs',
    appId: '1:892493235707:android:a435c1c5a8842cca48b75e',
    messagingSenderId: '892493235707',
    projectId: 'kiloapp-bfdaa',
    storageBucket: 'kiloapp-bfdaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzI69sUJ_oB7Hpjb1pzZtMo4gehs-2VLI',
    appId: '1:892493235707:ios:0e1dc3480435051848b75e',
    messagingSenderId: '892493235707',
    projectId: 'kiloapp-bfdaa',
    storageBucket: 'kiloapp-bfdaa.firebasestorage.app',
    iosBundleId: 'com.annaKiloApp.exerciseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzI69sUJ_oB7Hpjb1pzZtMo4gehs-2VLI',
    appId: '1:892493235707:ios:cf7532204515c30848b75e',
    messagingSenderId: '892493235707',
    projectId: 'kiloapp-bfdaa',
    storageBucket: 'kiloapp-bfdaa.firebasestorage.app',
    iosBundleId: 'com.example.exerciseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDebP8Z4auyoR4WnOLJpaqmlKNV71BuNX4',
    appId: '1:892493235707:web:a39a63ca1978a7cb48b75e',
    messagingSenderId: '892493235707',
    projectId: 'kiloapp-bfdaa',
    authDomain: 'kiloapp-bfdaa.firebaseapp.com',
    storageBucket: 'kiloapp-bfdaa.firebasestorage.app',
    measurementId: 'G-Q912Y8PNPC',
  );

}